create table Customers(
    CUSTID VARCHAR(10) NOT NULL PRIMARY KEY,
    CUSTNAME VARCHAR(20) NOT NULL,
    CUSTADDRESS VARCHAR(50) NOT NULL,
    CUSTPASSWORD VARCHAR(10) NOT NULL
);

CREATE TABLE Orders(
    ORDERID VARCHAR(10) NOT NULL PRIMARY KEY,
    ORDERNAME VARCHAR(20) NOT NULL,
    ORDERDATE DATE NOT NULL,
    QTY INT(3),
    CUSTID VARCHAR(10) NOT NULL
);

CREATE TABLE Payments(
    PAYMENTID VARCHAR(10) NOT NULL PRIMARY KEY,
    AMOUNT INT(6) NOT NULL,
    PAYMENTTYPE VARCHAR(10) NOT NULL,
    TAX INT(6),
    ORDERID VARCHAR(10) NOT NULL 
);

CREATE TABLE Credit(
    CARDNO INT(16) NOT NULL PRIMARY KEY,
    CCNO INT(3) NOT NULL ,
    EXPDATE DATE NOT NULL,
    CARDTYPE VARCHAR(10),
    PAYMENTID VARCHAR(10) NOT NULL
);

CREATE TABLE Admins(
    ADMINID VARCHAR(10) NOT NULL PRIMARY KEY,
    ADMINNAME VARCHAR(20) NOT NULL,
    ADMINPASSWORD VARCHAR(10) NOT NULL,
    REGDATE DATE,
    LOGINSTATUS BOOLEAN
);

CREATE TABLE Port(
    PORTID VARCHAR(10) NOT NULL PRIMARY KEY,
    PORTNAME VARCHAR(20) NOT NULL
);

CREATE TABLE Ships(
    SHIPID VARCHAR(10) NOT NULL PRIMARY KEY,
    ROUTE VARCHAR(10) NOT NULL,
    LOCATION VARCHAR(20) ,
    DOCKTIME TIME,
    NOOFCONTAINERS INT(4),
    WEIGHT INT(4),
    REFUELDURATION INT(3),
    PRICEPERHOUR INT(6),
    ARRIVAL_DATE DATE,
    PORTID VARCHAR(10) NOT NULL

);

CREATE TABLE Containers(
    CONTAINERID VARCHAR(10) NOT NULL PRIMARY KEY,
    GOODS_NAME VARCHAR(20),
    SHIPID VARCHAR(10) NOT NULL UNIQUE
);

ALTER TABLE Orders
ADD CONSTRAINT fk_1
FOREIGN KEY (CUSTID)
REFERENCES CUSTOMERS(CUSTID);


ALTER TABLE PAYMENT
ADD CONSTRAINT fk_2
FOREIGN KEY (ORDERID)
REFERENCES ORDERS(ORDERID);

ALTER TABLE Credit
ADD CONSTRAINT fk_3
FOREIGN KEY (PAYMENTID)
REFERENCES Payments(PAYMENTID);

ALTER TABLE Ships
ADD CONSTRAINT fk_4
FOREIGN KEY (PORTID)
REFERENCES port(PORTID);

ALTER TABLE CONTAINERS
ADD CONSTRAINT fk_5
FOREIGN KEY (SHIPID)
REFERENCES SHIPS(SHIPID);